function Q = rotation_matrix(phi, psi, theta)
    Q = [cos(phi)*cos(psi) - sin(phi)*cos(theta)*sin(psi), ...
        -sin(phi)*cos(psi) - cos(phi)*cos(theta)*sin(psi), ...
         sin(theta)*sin(psi);
        
         cos(phi)*sin(psi) + sin(phi)*cos(theta)*cos(psi), ...
        -sin(phi)*sin(psi) + cos(phi)*cos(theta)*cos(psi), ...
        -sin(theta)*cos(phi);
        
         sin(phi)*sin(theta), ...
         cos(phi)*sin(theta), ...
         cos(theta)];
end